name: Second
on: [push]
jobs:
    job1:
        name: First Job 
        runs-on: ubuntu-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2 
            - name: Step two
              run: echo "Today date is $(date)"
         
    job2:
        name: Second Job
        runs-on: windows-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: Write-Output "Today date is $(Get-Date -Format 'MM/dd/yyyy')"
    job3:
        name: Third Job 
        runs-on: macos-latest
        steps:
            - name: Step one
              uses: actions/checkout@v2 
            - name: Step two
              run: echo "Today date is $(date)"
         
    job4:
        name: Fourth Job
        runs-on: ubuntu-latest
        needs: [job1, job2, job3]
        steps:
            - name: Step one
              uses: actions/checkout@v2
            - name: Step two
              run: echo "Today date is $(date)"